// Manifest of every page in the zine, in reading order.
// To add more pages later: just append more filenames to this array
// and drop the matching images into assets/pages/ — nothing else
// needs to change, the book rebuilds itself from this list.
//
// A page is normally just a filename string. The very first page is
// special: it's a composite of two images (the photo underneath, the
// translucent vellum design on top), so it's described as an object
// instead. See script.js for how that's rendered.
//
// The translucent "vellum" treatment is applied automatically to the
// LAST page in this list too — currently the real back cover.

const PAGES = [
  { type: "cover-composite", bg: "cover-bg.jpg", overlay: "cover-overlay.jpg" },
  "page-02.jpg",
  "page-03.jpg",
  "page-04.jpg",
  "page-05.jpg",
  "page-06.jpg",
  "page-07.jpg",
  "page-08.jpg",
  "page-09.jpg",
  "page-10.jpg",
  "page-11.jpg",
  "page-12.jpg",
  "page-13.jpg",
  "page-14.jpg",
  "page-15.jpg",
  "page-16.jpg",
  "page-17.jpg",
  "page-18.jpg",
  "page-19.jpg",
  "page-20.jpg",
  "page-21.jpg",
  "page-22.jpg",
  "page-23.jpg",
  "page-24.jpg",
  "page-25.jpg",
  "page-26.jpg",
  "page-27.jpg",
  "page-28.jpg",
  "page-29.jpg",
  "page-30.jpg",
  "page-31.jpg",
  "page-32.jpg",
  "page-33.jpg",
  "page-34.jpg",
  "page-35.jpg",
  "page-36.jpg",
  "page-37.jpg",
  "page-38.jpg",
  "page-39.jpg",
  "page-40.jpg",
  "page-41.jpg",
  "page-42.jpg",
  "page-43.jpg",
  "page-44.jpg",
  "page-45.jpg",
  "page-46.jpg",
  "page-47.jpg",
  "page-48.jpg",
  "page-49.jpg",
  "page-50.jpg",
  "page-51.jpg",
  "page-52.jpg",
  "page-53.jpg",
  "page-54.jpg",
  "page-55.jpg",
  "page-56.jpg",
  "page-57.jpg",
  "page-58.jpg",
  "page-59.jpg",
  "page-60.jpg",
  "page-61.jpg",
  "page-62.jpg",
  "page-63.jpg",
  "page-64.jpg",
  "page-65.jpg",
  "page-66.jpg",
  "page-67.jpg",
  "page-68.jpg",
  "page-69.jpg",
  "page-70.jpg",
  "page-71.jpg",
  { type: "cover-composite", bg: "page-72.jpg", overlay: "page-73.jpg" },
];
